// Comprehensive list of car brands sold in Vietnam
export const VIETNAM_CAR_BRANDS = [
  'Acura',
  'Alfa Romeo',
  'Aston Martin',
  'Audi',
  'Bentley',
  'BMW',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Citroën',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'Dodge',
  'Ferrari',
  'Fiat',
  'Ford',
  'Genesis',
  'GMC',
  'Honda',
  'Hummer',
  'Hyundai',
  'Infiniti',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Lamborghini',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Maserati',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Ram',
  'Renault',
  'Rolls-Royce',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'VinFast',
  'Volkswagen',
  'Volvo',
].sort();

// Car models by brand (popular models in Vietnam)
export const VIETNAM_CAR_MODELS = {
  'Acura': ['ILX', 'TLX', 'RLX', 'MDX', 'RDX', 'NSX'],
  'Alfa Romeo': ['Giulia', 'Stelvio', '4C'],
  'Aston Martin': ['DB11', 'DBS', 'Vantage', 'DBX'],
  'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron'],
  'Bentley': ['Continental GT', 'Flying Spur', 'Bentayga', 'Mulsanne'],
  'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'i8', 'iX'],
  'Bugatti': ['Chiron', 'Veyron'],
  'Buick': ['Enclave', 'Encore', 'Envision', 'LaCrosse', 'Regal'],
  'Cadillac': ['CT4', 'CT5', 'CT6', 'XT4', 'XT5', 'XT6', 'Escalade'],
  'Chevrolet': ['Spark', 'Malibu', 'Camaro', 'Corvette', 'Trailblazer', 'Trax', 'Equinox', 'Traverse', 'Tahoe', 'Suburban', 'Colorado', 'Silverado'],
  'Chrysler': ['300', 'Pacifica', 'Voyager'],
  'Citroën': ['C3', 'C4', 'C5 Aircross', 'Berlingo'],
  'Dacia': ['Duster', 'Logan', 'Sandero'],
  'Daewoo': ['Matiz', 'Gentra', 'Lacetti', 'Magnus'],
  'Daihatsu': ['Terios', 'Xenia', 'Gran Max'],
  'Dodge': ['Challenger', 'Charger', 'Durango', 'Journey'],
  'Ferrari': ['488', 'F8', 'Roma', 'Portofino', 'SF90', '812', 'Purosangue'],
  'Fiat': ['500', 'Panda', 'Tipo', 'Ducato'],
  'Ford': ['Fiesta', 'Focus', 'Mondeo', 'Mustang', 'EcoSport', 'Escape', 'Edge', 'Explorer', 'Expedition', 'Ranger', 'F-150', 'Everest', 'Territory', 'Transit'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'GMC': ['Terrain', 'Acadia', 'Yukon', 'Sierra', 'Canyon'],
  'Honda': ['Brio', 'City', 'Civic', 'Accord', 'CR-V', 'HR-V', 'BR-V', 'Pilot', 'Odyssey', 'Jazz'],
  'Hummer': ['H1', 'H2', 'H3', 'EV'],
  'Hyundai': ['i10', 'Accent', 'Elantra', 'Sonata', 'Azera', 'Kona', 'Tucson', 'Santa Fe', 'Palisade', 'Venue', 'Creta', 'Ioniq'],
  'Infiniti': ['Q50', 'Q60', 'Q70', 'QX30', 'QX50', 'QX60', 'QX80'],
  'Isuzu': ['D-Max', 'mu-X'],
  'Jaguar': ['XE', 'XF', 'XJ', 'F-Type', 'E-Pace', 'F-Pace', 'I-Pace'],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
  'Kia': ['Morning', 'Rio', 'Cerato', 'K3', 'K5', 'K8', 'Seltos', 'Sportage', 'Sorento', 'Carnival', 'Telluride', 'EV6'],
  'Lamborghini': ['Huracán', 'Aventador', 'Urus'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Range Rover Sport', 'Range Rover'],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'RC', 'LC', 'UX', 'NX', 'RX', 'GX', 'LX'],
  'Lincoln': ['Corsair', 'Nautilus', 'Aviator', 'Navigator'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'MC20', 'GranTurismo'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-8', 'CX-9', 'MX-5', 'BT-50'],
  'McLaren': ['570S', '720S', 'GT', 'Artura'],
  'Mercedes-Benz': ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'CLA', 'CLS', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'G-Class', 'AMG GT', 'EQC', 'EQS', 'V-Class'],
  'MG': ['ZS', 'HS', '5', '6', 'RX5'],
  'Mini': ['Cooper', 'Clubman', 'Countryman'],
  'Mitsubishi': ['Mirage', 'Attrage', 'Lancer', 'Outlander', 'Eclipse Cross', 'Pajero Sport', 'Triton', 'Xpander'],
  'Nissan': ['Almera', 'Sunny', 'Sylphy', 'Teana', 'GT-R', 'Kicks', 'Juke', 'X-Trail', 'Terra', 'Navara', 'Patrol'],
  'Opel': ['Corsa', 'Astra', 'Insignia', 'Crossland', 'Grandland'],
  'Peugeot': ['208', '308', '508', '2008', '3008', '5008', 'Traveller'],
  'Porsche': ['718', '911', 'Panamera', 'Taycan', 'Macan', 'Cayenne'],
  'Ram': ['1500', '2500', '3500'],
  'Renault': ['Kwid', 'Duster', 'Captur', 'Koleos', 'Talisman'],
  'Rolls-Royce': ['Ghost', 'Wraith', 'Dawn', 'Phantom', 'Cullinan'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'BRZ', 'WRX'],
  'Suzuki': ['Celerio', 'Swift', 'Ciaz', 'Ertiga', 'XL7', 'Vitara', 'Jimny', 'Carry'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck', 'Roadster'],
  'Toyota': ['Wigo', 'Vios', 'Corolla', 'Camry', 'Avalon', 'Yaris', 'Raize', 'Rush', 'Avanza', 'Innova', 'Veloz', 'Fortuner', 'Hilux', 'Land Cruiser', 'Prado', 'Alphard', 'Vellfire', 'Sienna', 'Corolla Cross', 'C-HR', 'RAV4', 'Highlander', 'bZ4X'],
  'VinFast': ['Fadil', 'Lux A2.0', 'Lux SA2.0', 'VF 5', 'VF 6', 'VF 7', 'VF 8', 'VF 9', 'VF e34'],
  'Volkswagen': ['Polo', 'Golf', 'Jetta', 'Passat', 'Arteon', 'Tiguan', 'Touareg', 'Atlas', 'ID.4', 'ID.Buzz'],
  'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90', 'C40', 'EX30', 'EX90'],
};
